# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180703_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default='1'),
        ),
    ]
