# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180703_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwd',
        ),
    ]
