# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20180703_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaires',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
