# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20180703_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaires',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='questionnaire_type',
            field=models.CharField(max_length=50),
        ),
    ]
