# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20180704_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='option',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='title',
            new_name='questionnaire',
        ),
    ]
